In [30]:
#Data Preprocessing

#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the Dataset
dataset_path='data.csv'
dataset=pd.read_csv(dataset_path)
X=dataset.iloc[:,:6].values # X matrix of input features
y=dataset.iloc[:,-1:].values # y vector of output values

#Adding Polynomial terms for non-linear decision boundaries
from sklearn.preprocessing import PolynomialFeatures
poly_features= PolynomialFeatures(degree=7)
X=poly_features.fit_transform(X)
"""
#Encoding of categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y=labelencoder_y.fit_transform(y)"""
#Split Dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)


In [31]:
#Fitting to Training Set
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(multi_class="ovr")
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
#Prediction on TestSet
y_pred=classifier.predict(X_test)

#Model Performance
from sklearn import metrics
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Logistic Regression model accuracy(in %): 98.09523809523809
[[ 6  1  0  0]
 [ 0  6  0  0]
 [ 1  0 86  0]
 [ 0  0  0  5]]
                    precision    recall  f1-score   support

       Coronavirus       0.86      0.86      0.86         7
         Influenza       0.86      1.00      0.92         6
              None       1.00      0.99      0.99        87
Seasonal Allergies       1.00      1.00      1.00         5

          accuracy                           0.98       105
         macro avg       0.93      0.96      0.94       105
      weighted avg       0.98      0.98      0.98       105



In [33]:
import pickle
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(classifier, open(filename, 'wb'))