In [6]:
#Data Preprocessing

#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the Dataset
dataset_path='data.csv'
dataset=pd.read_csv(dataset_path)
X=dataset.iloc[:,:6].values # X matrix of input features
y=dataset.iloc[:,-1:].values # y vector of output values

"""
#Encoding of categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y=labelencoder_y.fit_transform(y)"""
#Split Dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)


In [7]:
#Fitting to Training Set
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(multi_class="ovr")
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
#Prediction on TestSet
y_pred=classifier.predict(X_test)

#Model Performance
from sklearn import metrics
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Logistic Regression model accuracy(in %): 97.14285714285714
[[ 6  0  0  1]
 [ 1  5  0  0]
 [ 0  0 87  0]
 [ 1  0  0  4]]
                    precision    recall  f1-score   support

       Coronavirus       0.75      0.86      0.80         7
         Influenza       1.00      0.83      0.91         6
              None       1.00      1.00      1.00        87
Seasonal Allergies       0.80      0.80      0.80         5

          accuracy                           0.97       105
         macro avg       0.89      0.87      0.88       105
      weighted avg       0.97      0.97      0.97       105



In [9]:
#User Input
print("Type 1 for yes and 0 for no for the following questions:")
trip = int(input(" Have you gone on a trip in the past month?"))
fever = int(input("Do you currently have a fever?"))
eye = int(input("Did your eyes itch in the past week?"))
nose = int(input("Do you have a runny nose?"))
breath = int(input("Have you had trouble breathing recently?"))
cough = int(input("Have you coughed much lately?"))

y_output_probab = classifier.predict_proba([[trip, fever, eye, nose, breath, cough]])
print("\nProbabilities")
for i,p in enumerate(y_output_probab[0]):
    print(classifier.classes_[i]+": "+str((p*100)))

y_output = classifier.predict([[trip, fever, eye, nose, breath, cough]])
print(y_output)



Type 1 for yes and 0 for no for the following questions:

Probabilities
Coronavirus: 95.27103736234653
Influenza: 3.514232590204216
None: 0.1729391839390742
Seasonal Allergies: 1.0417908635101696
['Coronavirus']


In [11]:
import pickle
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(classifier, open(filename, 'wb'))